<?php

namespace Proxies\__CG__\Pedagogie\PedagogieBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Nature extends \Pedagogie\PedagogieBundle\Entity\Nature implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'id', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'nature', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'c', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'td', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'tp', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'description', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'matieres');
        }

        return array('__isInitialized__', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'id', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'nature', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'c', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'td', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'tp', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'description', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Nature' . "\0" . 'matieres');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Nature $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNature($nature)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNature', array($nature));

        return parent::setNature($nature);
    }

    /**
     * {@inheritDoc}
     */
    public function getNature()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNature', array());

        return parent::getNature();
    }

    /**
     * {@inheritDoc}
     */
    public function setC($c)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setC', array($c));

        return parent::setC($c);
    }

    /**
     * {@inheritDoc}
     */
    public function getC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getC', array());

        return parent::getC();
    }

    /**
     * {@inheritDoc}
     */
    public function setTd($td)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTd', array($td));

        return parent::setTd($td);
    }

    /**
     * {@inheritDoc}
     */
    public function getTd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTd', array());

        return parent::getTd();
    }

    /**
     * {@inheritDoc}
     */
    public function setTp($tp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTp', array($tp));

        return parent::setTp($tp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTp', array());

        return parent::getTp();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function addMatiere(\Pedagogie\PedagogieBundle\Entity\Matiere $matieres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMatiere', array($matieres));

        return parent::addMatiere($matieres);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMatiere(\Pedagogie\PedagogieBundle\Entity\Matiere $matieres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMatiere', array($matieres));

        return parent::removeMatiere($matieres);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatieres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatieres', array());

        return parent::getMatieres();
    }

}
