<?php

namespace Pedagogie\PedagogieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DevoirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevoirRepository extends EntityRepository
{
	public function findByDepartement($departement)
	{
			$qb = $this->createQueryBuilder('dev');
			$qb ->join('dev.departements', 'dep' ,'WITH', 'dep.id = \''.$departement->getId().'\'' ); // Puis on filtre sur le nom des catégories à l'aide d'un IN
			// Enfin, on retourne le résultat
			return $qb->getQuery()->getResult();
	}
	
	public function findByFiliere($filiere)
	{
			$qb = $this->createQueryBuilder('dev');
			$qb ->join('dev.filieres', 'fil' ,'WITH', 'fil.id = \''.$filiere->getId().'\'' ); // Puis on filtre sur le nom des catégories à l'aide d'un IN
			// Enfin, on retourne le résultat
			return $qb->getQuery()->getResult();
	}
	
	public function findByClasse($classes)
	{
			$qb = $this->createQueryBuilder('dev');
			$qb ->join('dev.classes', 'cls' ,'WITH', 'cls.id = \''.$classes->getId().'\'' ); // Puis on filtre sur le nom des catégories à l'aide d'un IN
			// Enfin, on retourne le résultat
			return $qb->getQuery()->getResult();
	}
	
	public function findByGroupe($groupe)
	{
			$qb = $this->createQueryBuilder('dev');
			$qb ->join('dev.groupes', 'g' ,'WITH', 'g.id = \''.$groupe->getId().'\'' ); // Puis on filtre sur le nom des catégories à l'aide d'un IN
			// Enfin, on retourne le résultat
			return $qb->getQuery()->getResult();
	}
	
	public function findByEnseignant($enseignant)
	{
			$qb = $this->createQueryBuilder('dev');
			$qb ->join('dev.enseignants', 'ens' ,'WITH', 'ens.id = \''.$enseignant->getId().'\'' ); // Puis on filtre sur le nom des catégories à l'aide d'un IN
			// Enfin, on retourne le résultat
			return $qb->getQuery()->getResult();
	}
	
	public function findByNature($natures)
	{
			$qb = $this->createQueryBuilder('dev');
			$qb ->join('dev.natures', 'nat' ,'WITH', 'nat.id = \''.$natures->getId().'\'' ); // Puis on filtre sur le nom des catégories à l'aide d'un IN
			// Enfin, on retourne le résultat
			return $qb->getQuery()->getResult();
	}
	
}
