<?php

namespace Pedagogie\PedagogieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnseignantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignantRepository extends EntityRepository
{
		public function findByMatiere($matiere,$departement)
	{
			$qb = $this->createQueryBuilder('e');
			$qb ->join('e.matieres', 'm' ,'WITH', 'm.id= \''.$matiere->getId().'\''  );
			//$qb->where('e.departement = :departement')->setParameter('departement', $departement->getDepartement());
			// Enfin, on retourne le résultat
			return $qb->getQuery()->getResult();
	}
	
	public function findExistDepartement($nomens,$departement)
	{
			$qb = $this->createQueryBuilder('ens');
			$qb->where('ens.enseigant = :nomens')->setParameter('nomens', $nomens);
			$qb ->join('ens.departement', 'dep' ,'WITH', 'dep.id = \''.$departement->getId().'\'' ); // Puis on filtre sur le nom des catégories à l'aide d'un IN
			// Enfin, on retourne le résultat
			return $qb->getQuery()->getOneOrNullResult();
	}
}
