<?php

namespace Pedagogie\PedagogieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FiliereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiliereRepository extends EntityRepository
{
	public function findExist($nomfil)
	{
			$qb = $this->createQueryBuilder('fil');
			$qb->where('fil.filiere = :nomfil')->setParameter('nomfil', $nomfil);
		
			// Enfin, on retourne le résultat
			return $qb->getQuery()->getOneOrNullResult();
	}
}
