<?php

namespace Proxies\__CG__\Pedagogie\PedagogieBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Grades extends \Pedagogie\PedagogieBundle\Entity\Grades implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'id', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'grades', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'code', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'c', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'td', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'tp', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'enseignants');
        }

        return array('__isInitialized__', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'id', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'grades', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'code', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'c', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'td', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'tp', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Grades' . "\0" . 'enseignants');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Grades $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrades($grades)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrades', array($grades));

        return parent::setGrades($grades);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrades()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrades', array());

        return parent::getGrades();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', array());

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setC($c)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setC', array($c));

        return parent::setC($c);
    }

    /**
     * {@inheritDoc}
     */
    public function getC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getC', array());

        return parent::getC();
    }

    /**
     * {@inheritDoc}
     */
    public function setTd($td)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTd', array($td));

        return parent::setTd($td);
    }

    /**
     * {@inheritDoc}
     */
    public function getTd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTd', array());

        return parent::getTd();
    }

    /**
     * {@inheritDoc}
     */
    public function setTp($tp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTp', array($tp));

        return parent::setTp($tp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTp', array());

        return parent::getTp();
    }

    /**
     * {@inheritDoc}
     */
    public function addEnseignant(\Pedagogie\PedagogieBundle\Entity\Enseignant $enseignants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEnseignant', array($enseignants));

        return parent::addEnseignant($enseignants);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEnseignant(\Pedagogie\PedagogieBundle\Entity\Enseignant $enseignants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEnseignant', array($enseignants));

        return parent::removeEnseignant($enseignants);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnseignants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnseignants', array());

        return parent::getEnseignants();
    }

}
