<?php

namespace Proxies\__CG__\Pedagogie\PedagogieBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Groupe extends \Pedagogie\PedagogieBundle\Entity\Groupe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'id', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'groupe', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'departement', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'filiere', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'disciplines', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'classe', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'matieres', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'emplois', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'devoirs', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'voeux');
        }

        return array('__isInitialized__', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'id', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'groupe', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'departement', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'filiere', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'disciplines', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'classe', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'matieres', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'emplois', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'devoirs', '' . "\0" . 'Pedagogie\\PedagogieBundle\\Entity\\Groupe' . "\0" . 'voeux');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Groupe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroupe($groupe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroupe', array($groupe));

        return parent::setGroupe($groupe);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupe', array());

        return parent::getGroupe();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartement(\Pedagogie\PedagogieBundle\Entity\Departement $departement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartement', array($departement));

        return parent::setDepartement($departement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartement', array());

        return parent::getDepartement();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiliere(\Pedagogie\PedagogieBundle\Entity\Filiere $filiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiliere', array($filiere));

        return parent::setFiliere($filiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiliere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiliere', array());

        return parent::getFiliere();
    }

    /**
     * {@inheritDoc}
     */
    public function addDiscipline(\Pedagogie\PedagogieBundle\Entity\Discipline $disciplines)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDiscipline', array($disciplines));

        return parent::addDiscipline($disciplines);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDiscipline(\Pedagogie\PedagogieBundle\Entity\Discipline $disciplines)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDiscipline', array($disciplines));

        return parent::removeDiscipline($disciplines);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisciplines()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisciplines', array());

        return parent::getDisciplines();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasse(\Pedagogie\PedagogieBundle\Entity\Classe $classe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasse', array($classe));

        return parent::setClasse($classe);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasse', array());

        return parent::getClasse();
    }

    /**
     * {@inheritDoc}
     */
    public function addMatiere(\Pedagogie\PedagogieBundle\Entity\Matiere $matieres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMatiere', array($matieres));

        return parent::addMatiere($matieres);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMatiere(\Pedagogie\PedagogieBundle\Entity\Matiere $matieres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMatiere', array($matieres));

        return parent::removeMatiere($matieres);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatieres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatieres', array());

        return parent::getMatieres();
    }

    /**
     * {@inheritDoc}
     */
    public function addEmplois(\Pedagogie\PedagogieBundle\Entity\Emploi $emplois)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmplois', array($emplois));

        return parent::addEmplois($emplois);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmplois(\Pedagogie\PedagogieBundle\Entity\Emploi $emplois)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmplois', array($emplois));

        return parent::removeEmplois($emplois);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmplois()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmplois', array());

        return parent::getEmplois();
    }

    /**
     * {@inheritDoc}
     */
    public function addDevoir(\Pedagogie\PedagogieBundle\Entity\Devoir $devoirs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDevoir', array($devoirs));

        return parent::addDevoir($devoirs);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDevoir(\Pedagogie\PedagogieBundle\Entity\Devoir $devoirs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDevoir', array($devoirs));

        return parent::removeDevoir($devoirs);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevoirs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevoirs', array());

        return parent::getDevoirs();
    }

    /**
     * {@inheritDoc}
     */
    public function addVoeux(\Pedagogie\PedagogieBundle\Entity\Voeux $voeux)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVoeux', array($voeux));

        return parent::addVoeux($voeux);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVoeux(\Pedagogie\PedagogieBundle\Entity\Voeux $voeux)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVoeux', array($voeux));

        return parent::removeVoeux($voeux);
    }

    /**
     * {@inheritDoc}
     */
    public function getVoeux()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVoeux', array());

        return parent::getVoeux();
    }

}
